/*
A Pig Latin is an encrypted word in English, generated by placing the first letter of each word at the end, and then adding "ay" to the end.

For words that begin with consonant sounds, these are also known as consonant blends (two letters that make one sound: e.g., black, slack, clown). The initial consonant blend (or two letters) is moved to the end of the word, then "ay" is added, as in the following examples:[15]

"pig" = "igpay"
"latin" = "atinlay"
"banana" = "ananabay"
"black" = "ackblay"
For words that begin with vowel sounds, "way" is added to the end:[15]

"a" = "away"
"open" = "openway"

*/

var translatePigLatin = function(word){
    // Matches one or more consecutive characters at the start of the string
    // that are NOT lowercase vowels (a, e, i, o, u).
    // ^ outside brackets means “match from the very start of the string”.
    // [^aeiou] → any character except lowercase vowels
    // + → one or more
    // g flag → global search (though here it will only match once due to ^)
    // Without /g, regex methods like .match() or .replace() stop after the first match
    // With /g, they find all matches in the string.
    let regex = /^[^aeiou]+/gi
    let consonants = word.match(regex);

    console.log("Word: " + word + ", Consonants: " + consonants + ", Begins With Consonant: " + regex.test(word));

//    if (consonants is empty) {
//        add 'way' to str
//    }
//    else {
//        replace beginning of str with '', add consonants and then the 'ay'
//    }
    return (consonants === null) ? word.concat('way').toLowerCase() : word.replace(regex, '').concat(consonants).concat('ay').toLowerCase();
}

// TEST CODE
var str1 = "Pig"
var str2 = "Latin"
var str3 = "banana"
var str4 = "black"
var str5 = "away"
var str6 = "open"
var str7 = "tAcocat"

console.log(translatePigLatin(str1));
console.log(translatePigLatin(str2));
console.log(translatePigLatin(str3));
console.log(translatePigLatin(str4));
console.log(translatePigLatin(str5));
console.log(translatePigLatin(str6));
console.log(translatePigLatin(str7));