name: "Selenium Grid Docker Demo"

# Containers
services:
  # 1st Container called selenium-hub
  selenium-hub:
    image: selenium/hub
    ports:
      - "4442:4442"
      - "4443:4443" # NEW
      - "4444:4444" # NEW
    environment:
      # 16 browsers at a time on this grid
      GRID_MAX_SESSION: 16
      # Grid timeouts are recommended to be 300 seconds
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300

  # 2nd Container called chrome
  chrome:
    image: selenium/node-chrome

    # has to wait selenium-hub to be up & running before this can be successfully marked as created
    depends_on:
      - selenium-hub

    environment:
      # link to selenium hub container
      SE_EVENT_BUS_HOST: selenium-hub # NEW
      #HUB_PORT_4444_TCP_ADDR: selenium-hub # REMOVED
      #HUB_PORT_4444_TCP_PORT: 4444 # REMOVED


      # 2 Chrome browsers per container
      SE_NODE_MAX_SESSIONS: 2
      # NODE_MAX_SESSION: 2 # REMOVED
      # NODE_MAX_INSTANCES: 2 # REMOVED
    # volumes:
    #   - /dev/shm:/dev/shm

  # 3rd Container called firefox
  firefox:
    image: selenium/node-firefox

    # has to wait selenium-hub to be up & running before this can be successfully marked as created
    depends_on:
      - selenium-hub
    environment:

      # link to selenium hub container
      SE_EVENT_BUS_HOST: selenium-hub # NEW
      #HUB_PORT_4444_TCP_ADDR: selenium-hub # REMOVED
      #HUB_PORT_4444_TCP_PORT: 4444 # REMOVED

      # 4 Firefox browsers per container
      SE_NODE_MAX_SESSIONS: 4 # NEW
      # NODE_MAX_SESSION: 4 # REMOVED
      # NODE_MAX_INSTANCES: 4 # REMOVED
